# Generated by Django 5.2.8 on 2026-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_user_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_agreement_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
